### ISSUE TITLE
Navigation bar isn't responding

### ISSUE THREAD

**Issue by RandiHirushini** [RandiHirushini/slider#1]
Navigation bar is not functioning as expected. It does not let the user to go to the other item.

**Comment by GayanthaPeris** [comment]
Can you check the browser's console for any error messages when you click on the navigation links? It might provide valuable information about the issue.

**Comment by MaheshiMorakanda** [comment]
Review Navigation Bar Code - Start by looking through the navigation bar's source code. Check for any potential causes of the issue, such as missing links, erroneous HTML/CSS/JavaScript, or syntax mistakes. The anchor tags (a>) that identify the navigation links should receive special attention.

**Comment by RandiHirushini** [comment]
I think the issue might be related to an incorrect URL configuration for the navigation links. I'll take a look at the code and see if adjusting the URLs resolves the problem.

**Comment by GayanthaPeris** [comment]
Keep us updated if it was resolved.

**Comment by MaheshiMorakanda** [comment]
You appear to be working on this problem already. To avoid any issues, I'll work with you in coordination.

**Comment by RandiHirushini** [comment]
The issue has been resolved with the recent update. The navigation bar is now functioning as we expected earlier.  I'll be closing this issue. Feel free to reopen it if any related problems arise. Good luck team
