### ISSUE TITLE
Database connectivity

### ISSUE THREAD

**Issue by RandiHirushini** [RandiHirushini/slider#2]
Database is not connected as expected. Information entered is not sored and reflected in the database.

**Comment by MaheshiMorakanda** [comment]
Test Database Connection - Attempt to connect to the database and carry out a fundamental operation, such as inserting a test record, in a simple test script. This will enable you to determine whether the logic of your application or the database connection itself is the problem.

Check Database Permissions - Make sure the user credentials used to connect to the database have the read and write rights required.

**Comment by GayanthaPeris** [comment]
Verify Database Service Status
Make sure the database service is up and running. If you are using a remote database service, check its status and ensure there are no reported outages or maintenance happening.

**Comment by MaheshiMorakanda** [comment]
Firewall and Network Settings - Since our database is housed on a distant server, make sure that inbound connections to the database are permitted by checking the firewall and network settings.

**Comment by RandiHirushini** [comment]
The issue arose due to a problem with database creation on the Xampp server while using SQL. Consequently, I took the initiative to troubleshoot the database setup and successfully made the necessary modifications to ensure it works as expected.

**Comment by RandiHirushini** [comment]
Now, the issue has been resolved. The database is properly configured, enabling smooth functionality and interaction with the application's data. Thanks for the support.
