### ISSUE TITLE
Invalid Email or Password

### ISSUE THREAD

**Issue by MaheshiMorakanda** [RandiHirushini/slider#3]
When the password does not match with the email the respective error message is not shown. How can I proceed?

**Comment by GayanthaPeris** [comment]
check the code of the login process, including both the frontend and the backend. Might be an issue there.

**Comment by GayanthaPeris** [comment]
Yes there must be an issue with the error handling code.

**Comment by RandiHirushini** [comment]
Check  whether the login credentials stored in the database is correct? specially if the email you used is registered there? Could be a point that was missed.

**Comment by MaheshiMorakanda** [comment]
There was a slight issue with the code. I have fixed it. Now the error is showing as we expected. Thanks guys!
